 version: '2'
 services:
   web:
     build: ../src/cx-app
     volumes:
       - ./logs:/opt/logs
     ports:
       - "6001:6001"
   self-registration:
     build: ../src/cx-app/cx/self-registration
     volumes:
       - ../src/cx-app/cx/self-registration:/usr/src/app
       - /usr/src/app/node_modules
     ports:
       - "9080:8080"
       - "35729:35729"

   nginx:
     build: nginx-self
     ports:
       - "80:80"
     command: /bin/bash -c "nginx -g 'daemon off;'"
     depends_on:
       - web
       - self-registration

