 version: '2'
 services:
   web:
     build:
       context: ../middle_tier
       dockerfile: Dockerfile.development
     environment:
       - "CONFIG_PATH=/opt/middle_tier/services-aaf.json"
     volumes:
       - ./logs:/opt/logs
       - ../middle_tier:/opt/middle_tier
     ports:
       - "5000:5000"
   nginx:
     build: nginx-aaf-enrollment
     ports:
       - "8080:443"
     command: /bin/bash -c "nginx -g 'daemon off;'"
     volumes:
       - ../aaf-enrollment/build:/usr/src/app
     depends_on:
       - web
   redis:
     image: "redis:alpine"

