 version: '2'
 services:
   web:
     build:
       context: ../middle_tier
       dockerfile: Dockerfile.development
     environment:
       - "CONFIG_PATH=/opt/middle_tier/services-aaf.json"
     volumes:
       - ./logs:/opt/logs
       - ../middle_tier:/opt/middle_tier
     ports:
       - "5000:5000"
   ui:
     build: ../aaf-enrollment
     volumes:
       - ../aaf-enrollment:/usr/src/app
       - /usr/src/app/node_modules
     ports:
       - "9080:8080"
       - "35729:35729"

   nginx:
     build: nginx-aaf-enrollment
     ports:
       - "8080:80"
     command: /bin/bash -c "nginx -g 'daemon off;'"
     depends_on:
       - web
       - ui
   redis:
     image: "redis:alpine"

